import { useState, useEffect } from 'react'

import Head from 'next/head'

import { PT_Sans } from 'next/font/google'

import { HistoricalDates } from '@/components/common/historicalDates'

import { historicalDatesDate } from '@/components/common/historicalDates/config'
import { IHistoricalDatesDate } from '@/types/historicalDatesDateType'

const pt_sans = PT_Sans({ weight: ['400'], subsets: ['latin', 'cyrillic'] })

export const getStaticProps = async () => {

    return {
		props: {
			historicalDates: historicalDatesDate
		},
		revalidate: 60
	}
}

export default function Home({ historicalDates }: { historicalDates: IHistoricalDatesDate[]; }) {

	const [showPage, setShowPage] = useState(false);

  	useEffect(() => {
		const handleLoad = () => {
			setShowPage(true)
		}

		window.addEventListener('load', handleLoad)

		return () => {
			window.removeEventListener('load', handleLoad)
		}
	}, [])

	if (!showPage) {
		return null
	}

  	return (
		<>
			<Head>
				<title>Исторические даты</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>
			<main className={`${pt_sans.className}`}>
				<HistoricalDates historicalDates={historicalDates}/>
			</main>
		</>
	)
}
